### ISSUE TITLE
yarn dev 无法运行 报错xy-electron-sdk.node is not a valid Win32 application

### ISSUE THREAD

**Issue by 992695235** [xylink-com/xylink-electron-vue-demo#1]
![image](https://user-images.githubusercontent.com/37070619/91526921-4d71d400-e937-11ea-8bcd-2d1806859e36.png)

**Comment by luojinghui** [comment]
@992695235 
提供一下你的工程信息：

1. 系统版本
2. 系统位数
3. node版本
4. node位数
5. electron版本
6. electron位数

**Comment by 992695235** [comment]
您好，信息如下
系统版本：win10企业版 1909
系统位数 :64位
node版本:v12.18.3
node位数:64位
electron版本：5.0.13
electron位数：32位

**Comment by luojinghui** [comment]
@992695235 
怀疑是你的electron版本不是32位造成的，帮忙在主线程打印以下信息：
```js
  console.log("process.versions", {
    // electron 版本
    electrion: process.versions.electron,
    // ABI版本
    modules: process.versions.modules,
    // NODE版本
    node: process.versions.node,
    // V8 引擎版本
    v8: process.versions.v8,
    // chrome版本
    chrome: process.versions.chrome,
    // 架构信息
    architecture: process.env.PROCESSOR_ARCHITECTURE,
    userdata: app.getPath("userData"),
    appdata: app.getPath("appData"),
    arch: process.arch
  });
```
截图发给我看看。

**Comment by 992695235** [comment]
![image](https://user-images.githubusercontent.com/37070619/91546871-ba946200-e955-11ea-8d3a-dac35f4e8351.png)

**Comment by luojinghui** [comment]
@992695235 
你的arch是x64,是64位版本的electron，需要使用ia32位electron，执行：
```bash
yarn add electron@5.0.13 -D --arch=ia32
#or
npm install electron@5.0.13 -D --arch=ia32
```
重新运行试试。

**Comment by 992695235** [comment]
![2](https://user-images.githubusercontent.com/37070619/91547772-f845ba80-e956-11ea-84d4-e652db0d6b99.gif)
好像是一样的结果，请看gif图

**Comment by luojinghui** [comment]
@992695235 
通过 yarn 命令安装32位electron版本有问题，做了修复，可以使用下面两种方式解决（任选一）：
方式一（当前项目）：
1. 删除node_modules文件夹
2. 删除yarn.lock文件
3. 删除`package.json`中 `devDependencies`的electron字段
4. 执行：`npm install electron@5.0.13 -D --arch=ia32`

方式二（新clone项目）：
1. 删除当前项目，重新clone一份repo（已更新配置32electron安装方式）
2. 按照 `README` 文件引导运行.

如果是使用 `yarn` 管理包，建议使用方式二测试

**Comment by 992695235** [comment]
按照最新说明运行成功，感谢
