### ISSUE TITLE
node_modules\@xylink\xy-electron-sdk\build\Release\xy-electron-sdk.node is not a valid Win32 

### ISSUE THREAD

**Issue by sohoorc** [xylink-com/xylink-electron-vue-demo#2]
执行 yarn dev

electron控制台提示 node_modules\@xylink\xy-electron-sdk\build\Release\xy-electron-sdk.node is not a valid Win32

**Comment by luojinghui** [comment]
Duplicate of https://github.com/xylink-com/xylink-electron-vue-demo/issues/1

请在另一个issue上尝试解决。
