### ISSUE TITLE
使用 getDeviceList 报错

### ISSUE THREAD

**Issue by kingsungl** [xylink-com/xylink-electron-vue-demo#4]
```js
// 页面上使用
const speaker = await this.xyRTC.getDeviceList("speaker");
```
+ electron 16.0.7
+ vue 3.0
+ typescript 4.1.5

<img width="633" alt="image" src="https://user-images.githubusercontent.com/10396758/162160415-1eaec2b0-d8c5-4461-8741-5cbfeaf262eb.png">

**Comment by luojinghui** [comment]
经过测试，在Vue3环境下使用Vue2的data变量语法会产生兼容问题，造成访问底层实例方法报错。
可以通过如下方式解决（选择其一即可）：
1. 使用vue3的标准语法创建xy electron sdk实例；
2. 将xy electron sdk实例绑定到外部变量上即可；
